{% set name = "tdameritrade" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7ef13cf4bbef50633df3d5e3f263bc6a4a301e4b2ff3397077927a9fae0c709a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tdameritrade-auth = tdameritrade.auth:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pandas >=0.22.0
    - requests >=2.22.0
    - selenium >=3.141.0

test:
  imports:
    - tdameritrade

about:
  home: http://github.com/timkpaine/tdameritrade
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python interface to TD Ameritrade

  description: |
    Python interface to TD Ameritrade
  dev_url: https://github.com/timkpaine/tdameritrade

extra:
  recipe-maintainers:
    - timkpaine
